#!/usr/bin/env bash
# Say Hello to Vasile, a modular script to build Argent Workstation/Argent Linux packages && ISO images using a clean squashfs + overlayfs chroot
# Main author : Ghiunhan Mamut (aka V3n3RiX) @ RogentOS Development Group
# Dependencies : kernel built with squashfs + overlayfs + loopback support && sys-fs/grub:2 && sys-fs/squashfs-tools && dev-libs/libisoburn && sys-fs/mtools
#

# Import our variables and functions

source /usr/lib/avasile/libavasile

# Vasile need root privileges and a proper kernel to run
# Also, running it in live mode is a really bad idea

checkroot
checkiflive
kernelconfig


case $1 in
	--makepkg)
		source /usr/share/avasile/makepkg
		;;
	--makeiso)
		source /usr/share/avasile/makeiso
		;;
	--resetmode)
		source /usr/share/avasile/modereset
		;;
	--usermode)
		source /usr/share/avasile/modereset
		source /usr/share/avasile/usermodeset
		;;
	--devmode)
		source /usr/share/avasile/modereset
		source /usr/share/avasile/devmodeset
		;;
	--help)
		echo -e ""
		echo -e "Usage: avasile [options]"
		echo -e ""
		echo -e "Options:"
		echo -e "--makepkg : build package/target in a clean squashed core"
		echo -e "--makeiso : build iso based on clean squashed core + targets"
		echo -e "--resetmode : reset INSTALLED Argent Workstation system state - You're on your own, you've been warned!"
		echo -e "--usermode : switch INSTALLED Argent Workstation system state to usermode - use binary packages from repositories"
		echo -e "--devmode : switch INSTALLED Argent Workstation system state to devmode (aka Gentoo mode) - use source packages from portage tree"
		echo -e "--help : display this help and exit"
		echo -e ""
		;;
	*)
		echo -e "error: no operation specified, use --help for help"
		;;
esac

exit 0
