#!/usr/bin/env bash
# Say Hello to Vasile, a modular script to build Kogaion/Argent Workstation Linux packages && ISO images using a clean squashfs + overlayfs chroot
# Main author : Ghiunhan Mamut (aka V3n3RiX) @ RogentOS Development Group
# Dependencies : kernel built with squashfs + overlayfs + loopback support && sys-fs/grub:2 && sys-fs/squashfs-tools && dev-libs/libisoburn && sys-fs/mtools
#


# Import our variables and functions


source /usr/lib/avasile/libavasile


# Vasile need root privileges and a proper kernel to run
# Also, running it in live mode is a really bad idea


checkroot
checkiflive
kernelconfig



case $1 in
	--makepkg)
		source /usr/share/avasile/makepkg
		;;
	--makeiso)
		source /usr/share/avasile/makeiso
		;;
	--resetmode)
		source /usr/share/avasile/modereset
		;;
	--usermode)
		source /usr/share/avasile/modereset
		source /usr/share/avasile/usermodeset
		;;
	--devmode)
		source /usr/share/avasile/modereset
		source /usr/share/avasile/devmodeset
		;;
	--srcmode)
		source /usr/share/vasile/modereset
		source /usr/share/vasile/srcmode
		;;

	--help)
		einfo "Usage: avasile [options]"
		einfo ""
		einfo "Options:"
		einfo "--makepkg : build package/target in a clean squashed core"
		einfo "--makeiso : build iso based on clean squashed core + targets"
		einfo "--resetmode : reset INSTALLED Argent system state - You're on your own, you've been warned!"
		einfo "--usermode : switch INSTALLED Argent system state to usermode - use binary packages from repositories"
		einfo "--devmode : switch INSTALLED Argent system state to devmode (aka Gentoo mode) - use source packages from portage tree"
		einfo "--srcmode : switch Argent Linux system state to source only mode (full Gentoo mode)"
		einfo "--help : display this help and exit"
		einfo ""
		;;
	*)
		eerror -e "error: no operation specified, use --help for help"
		;;

esac

exit 0
