#!/usr/bin/env bash

fetch_devmode_portage_tree() {
	if [[ ! -d /usr/portage/.git ]] ; then
		cd /usr/portage && git init > /dev/null 2>&1
		git remote add origin git://anongit.gentoo.org/repo/gentoo.git
		git pull --depth=1 origin master
		git branch -u origin/master master
		rm -rf /usr/portage/profiles/updates
	fi
}

set_devmode_portage_tree() {
	ln -sf /opt/kogaion-build/conf/intel/portage /etc/portage
	ln -sf /etc/portage/make.conf.amd64-devel /etc/portage/make.conf
	eselect profile set 1
	env-update
	. /etc/profile
}

main() {
	fetch_devmode_portage_tree
	set_devmode_portage_tree
}

main
