#!/usr/bin/env bash

# Vasile needs root privileges and a proper kernel to run

kernelconfig
checkroot

export local isoarch="x86"
export local isoname=""$releasename"-"$releaseversion"-"$isoarch""
export local tmpiso="/tmp/"$isoname""

makeisox86 () {
	mkdir -p "$tmpiso"
	mkdir -p ""$isoname"/livecd"
	mount -t squashfs "$chrootx86" "$tmpiso"
	rsync -aHAXr --progress "$tmpiso/" ""$isoname"/livecd/"
	umount "$tmpiso"
}

main () {
	chrootchecksumx86
	makeisox86
}

main
