#!/usr/bin/env bash

fetch_usermode_portage_tree() {
	if [[ ! -d /usr/portage/.git ]] ; then
		cd /usr/portage && git init > /dev/null 2>&1
		git remote add origin git://anongit.gentoo.org/repo/gentoo.git
		git config core.sparsecheckout true
		echo "profiles/*" >> .git/info/sparse-checkout
		echo "metadata/*" >> .git/info/sparse-checkout
		echo "eclass/*" >> .git/info/sparse-checkout
		echo ".gitignore" >> .git/info/sparse-checkout
		git pull --depth=1 origin master
		git branch -u origin/master master
		rm -rf /usr/portage/profiles/updates
	fi
}

set_usermode_portage_tree() {
	ln -sf /opt/kogaion-build/conf/intel/portage /etc/portage
	ln -sf /etc/portage/make.conf.amd64-user /etc/portage/make.conf
	eselect profile set 1
	env-update
	. /etc/profile
}

main() {
	fetch_usermode_portage_tree
	set_usermode_portage_tree
}

main
